export type Role = 'user' | 'assistant';
export const seed = {
  profile:{name:'Learner',email:'',avatar:'🐾',joinDate:new Date().toISOString(),dailyGoalXp:20,currentLanguage:'es',totalXp:0,streak:0,longestStreak:0,completedLessons:[] as string[],completedStories:[] as string[],lastActiveDate:new Date().toISOString().split('T')[0],todayXp:0,onboarded:false},
  languages:[{code:'es',name:'Spanish',flag:'🇪🇸',level:'A1',xp:0,totalXp:5000,streak:0},{code:'ja',name:'Japanese',flag:'🇯🇵',level:'A1',xp:0,totalXp:2500,streak:0},{code:'fr',name:'French',flag:'🇫🇷',level:'A1',xp:0,totalXp:1000,streak:0},{code:'de',name:'German',flag:'🇩🇪',level:'A1',xp:0,totalXp:1000,streak:0},{code:'zh',name:'Mandarin',flag:'🇨🇳',level:'A1',xp:0,totalXp:1000,streak:0},{code:'pt',name:'Portuguese',flag:'🇧🇷',level:'A1',xp:0,totalXp:1000,streak:0},{code:'ko',name:'Korean',flag:'🇰🇷',level:'A1',xp:0,totalXp:1000,streak:0},{code:'it',name:'Italian',flag:'🇮🇹',level:'A1',xp:0,totalXp:1000,streak:0},{code:'ru',name:'Russian',flag:'🇷🇺',level:'A1',xp:0,totalXp:1000,streak:0},{code:'ar',name:'Arabic',flag:'🇦🇪',level:'A1',xp:0,totalXp:1000,streak:0},{code:'hi',name:'Hindi',flag:'🇮🇳',level:'A1',xp:0,totalXp:1000,streak:0},{code:'nl',name:'Dutch',flag:'🇳🇱',level:'A1',xp:0,totalXp:1000,streak:0}],
  lessons:[
    {id:'l1',lang:'es',title:'Greetings & Introductions',description:'Learn to say hello and introduce yourself',type:'vocabulary',difficulty:'beginner',xpReward:50,duration:5,completed:false,locked:false},
    {id:'l2',lang:'es',title:'Numbers & Counting',description:'Master numbers 1–100 and basic counting',type:'vocabulary',difficulty:'beginner',xpReward:50,duration:7,completed:false,locked:false},
    {id:'l3',lang:'es',title:'Colors & Descriptions',description:'Describe objects with colors and adjectives',type:'vocabulary',difficulty:'beginner',xpReward:60,duration:8,completed:false,locked:false},
    {id:'l4',lang:'es',title:'Present Tense Verbs',description:'Conjugate regular verbs in present tense',type:'grammar',difficulty:'beginner',xpReward:80,duration:10,completed:false,locked:false},
    {id:'l5',lang:'es',title:'Family & Relationships',description:'Talk about your family members',type:'vocabulary',difficulty:'beginner',xpReward:60,duration:6,completed:false,locked:true},
    {id:'l6',lang:'es',title:'At the Restaurant',description:'Order food and handle dining situations',type:'vocabulary',difficulty:'intermediate',xpReward:90,duration:12,completed:false,locked:true},
    {id:'l7',lang:'es',title:'Travel Phrases',description:'Essential phrases for traveling',type:'vocabulary',difficulty:'intermediate',xpReward:100,duration:15,completed:false,locked:true},
    {id:'l8',lang:'es',title:'Past Tense',description:'Talk about events that already happened',type:'grammar',difficulty:'intermediate',xpReward:120,duration:18,completed:false,locked:true}
  ],
  questions:[
    {id:'q1',type:'multiple-choice',prompt:"What does '¿Cómo te llamas?' mean?",options:['How are you?','What is your name?','Where are you from?','How old are you?'],answer:'What is your name?',explanation:"'¿Cómo te llamas?' is used to ask someone's name."},
    {id:'q2',type:'multiple-choice',prompt:"Which word means 'red' in Spanish?",options:['Azul','Verde','Rojo','Amarillo'],answer:'Rojo',explanation:'Rojo = Red, Azul = Blue, Verde = Green, Amarillo = Yellow.'},
    {id:'q3',type:'translate',prompt:"Translate: 'The cat is on the table'",options:['El gato está en la mesa','El perro está debajo de la mesa','El gato está encima del sofá','La mesa está cerca del gato'],answer:'El gato está en la mesa',explanation:'Gato = cat, está = is, en = on, la mesa = the table.'},
    {id:'q4',type:'multiple-choice',prompt:"How do you say 'Good morning' in Spanish?",options:['Buenas noches','Buenas tardes','Buenos días','Hola'],answer:'Buenos días',explanation:'Buenos días = Good morning, Buenas tardes = Good afternoon, Buenas noches = Good night.'},
    {id:'q5',type:'multiple-choice',prompt:"What is the plural of 'el libro' (the book)?",options:['los libros','las libros','el libros','los libro'],answer:'los libros',explanation:"In Spanish, masculine nouns use 'los' for plural, and most words ending in a consonant add '-os'."},
    {id:'q6',type:'translate',prompt:"Translate: 'I want water, please'",options:['Quiero agua, por favor','Necesito comida, gracias','Quiero café, por favor','Dame agua'],answer:'Quiero agua, por favor',explanation:'Quiero = I want, agua = water, por favor = please.'},
    {id:'q7',type:'multiple-choice',prompt:"Which verb form is correct: 'Yo ___ estudiante' (I am a student)?",options:['estar','es','soy','somos'],answer:'soy',explanation:"'Soy' is the first-person singular form of 'ser', used for permanent states like identity."}
  ],
  stories:[
    {id:'s1',lang:'es',title:'El Mercado Mágico',language:'Spanish',flag:'🇪🇸',level:'A2',genre:'Fantasy',excerpt:'En el corazón de la ciudad antigua, había un mercado que solo aparecía al amanecer...',content:`En el corazón de la ciudad antigua, había un mercado que solo aparecía al amanecer. Los vendedores llegaban con sus carros llenos de frutas de colores extraños y especias de tierras lejanas.\n\nMaría, una niña curiosa de diez años, descubrió el mercado una mañana cuando salió temprano a buscar a su gato. Los puestos brillaban con una luz dorada, y los aromas llenaban el aire frío de la madrugada.\n\n—Buenos días, pequeña —dijo una anciana con una sonrisa amable—. ¿Buscas algo especial?\n\n—Busco a mi gato —respondió María—. Se llama Naranja porque tiene el pelo del color de las zanahorias.\n\nLa anciana señaló hacia el fondo del mercado. Allí, entre montañas de especias rojas y amarillas, un gato anaranjado dormía tranquilamente.\n\n—¡Naranja! —gritó María con alegría.\n\nEl gato abrió un ojo, bostezó, y se estiró perezosamente. Al regresar a casa, encontró en el bolsillo una semilla pequeña y brillante. La plantó en una maceta, y a la mañana siguiente había crecido una flor de color naranja.`,readTime:4,wordsCount:210,completed:false},
    {id:'s2',lang:'es',title:'La Ciudad de los Sueños',language:'Spanish',flag:'🇪🇸',level:'B1',genre:'Science Fiction',excerpt:'En el año 2150, los seres humanos podían compartir sus sueños con cualquier persona del mundo...',content:`En el año 2150, los seres humanos podían compartir sus sueños con cualquier persona del mundo gracias al dispositivo NeuroLink. Carlos trabajaba como Arquitecto de Sueños, diseñando experiencias para millones de personas.\n\nSu última creación era una ciudad flotante sobre las nubes, donde la gravedad funcionaba al revés y los edificios crecían hacia abajo como estalactitas brillantes.\n\nUna noche, mientras calibraba los parámetros de su ciudad, encontró algo inesperado: una puerta que no había diseñado él. Detrás de ella, había una mujer que construía jardines en el aire.\n\n—¿Quién eres? —preguntó Carlos.\n\n—Soy Elena, de Madrid —respondió ella—. Llevo años construyendo este jardín en mis sueños.\n\nLos dos arquitectos comenzaron a trabajar juntos sin haberse conocido en la realidad. Cuando Carlos finalmente buscó a Elena en el mundo real, la encontró trabajando en la misma empresa, solo tres pisos más arriba.`,readTime:5,wordsCount:195,completed:false},
    {id:'s3',lang:'ja',title:'Sakura no Hana',language:'Japanese',flag:'🇯🇵',level:'A1',genre:'Nature',excerpt:'毎年春になると、公園の桜の木が満開になります...',content:`毎年春になると、公園の桜の木が満開になります。白とピンクの花びらが風に舞い、まるで雪のようです。\n\n田中さんは毎朝、この公園を歩きます。今日は特別な日です。娘の誕生日だからです。\n\n「桜、きれいね」と田中さんは言いました。\n\n小さな女の子は目を丸くして、「ピンクの雪みたい！」と叫びました。\n\n二人は木の下に座って、お弁当を食べました。おにぎり、卵焼き、それからいちごのケーキ。\n\n花びらが一枚、ケーキの上に落ちました。女の子は笑って、「桜のプレゼントだ！」と言いました。`,readTime:3,wordsCount:120,completed:false},
    {id:'s4',lang:'fr',title:'Le Café du Coin',language:'French',flag:'🇫🇷',level:'A2',genre:'Slice of Life',excerpt:"Chaque matin, Pierre s'arrêtait au même café pour prendre son croissant et son café au lait...",content:`Chaque matin, Pierre s'arrêtait au même café pour prendre son croissant et son café au lait. C'était sa routine depuis vingt ans. Marie, la propriétaire, connaissait sa commande par cœur.\n\n—Votre café, monsieur Pierre —disait-elle avec un sourire chaleureux.\n\nUn matin d'octobre, une nouvelle cliente entra dans le café. Elle semblait perdue, tenant une carte de la ville dans ses mains.\n\n—Excusez-moi, parlez-vous anglais ? —demanda-t-elle avec un accent américain.\n\nPierre, qui avait étudié l'anglais au lycée, se leva.\n\n—Un peu, oui. Je peux vous aider ?\n\nLa jeune femme cherchait le musée d'Orsay. Pierre lui expliqua le chemin en mélangeant le français et l'anglais, avec beaucoup de gestes.\n\nElle rit de bon cœur. —Merci beaucoup ! Je m'appelle Sophie.\n\n—Pierre. Enchantée.`,readTime:4,wordsCount:175,completed:false}
  ],
  achievements:[{id:'a1',title:'First lesson',description:'Complete one backend-tracked lesson',icon:'✓',earned:false}],
  providers:[{id:'openai-compatible',name:'OpenAI compatible',kind:'llm',baseUrl:'http://localhost:11434/v1',apiKeyRef:'LINGOCLAW_OPENAI_KEY',status:'local',notes:'Works with Ollama, LM Studio, vLLM, or any OpenAI-shaped endpoint.',models:['qwen3:8b','llama3.2','gpt-4.1-mini']},{id:'anthropic',name:'Anthropic',kind:'llm',baseUrl:'https://api.anthropic.com/v1',apiKeyRef:'ANTHROPIC_API_KEY',status:'needs-key',notes:'Good fit for tutor chat.',models:['claude-sonnet-4-5','claude-haiku-4-5']}],
  roles:[{id:'tutor-chat',label:'Tutor chat',purpose:'Socratic corrections, grammar explanations, and adaptive conversation.',providerId:'anthropic',model:'claude-sonnet-4-5',temperature:0.7,enabled:true}],
  chatSessions:[] as any[], chatMessages:[] as any[]
};
